language: node_js
node_js:
- "node"
cache: npm
addons:
  ssh_known_hosts: travisawagner.com
before_install:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi
- openssl aes-256-cbc -K $encrypted_615321f5512c_key -iv $encrypted_615321f5512c_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./.deploy.sh
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^dev|master$"
