language: node_js
node_js:
- "node"
cache: npm
addons:
  ssh_known_hosts: travisawagner.com
env:
  global:
  - DEVELOPMENT_PATH="/home/travisaw/travisaw.com/test/dev/synth-patch-name-generator"
  - PRODUCTION_PATH="/home/travisaw/travisaw.com/test/pro/synth-patch-name-generator"
  - SSH_USER="travisaw"
  - SSH_HOST="travisawagner.com"
  - DEPLOY_IGNORE="./.deployignore"
before_install:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi # dont run if is a pull request
- bash ./decrypt.sh
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./.deploy.sh
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^dev|master$"
