language: node_js
env:
  global:
  - DEVELOPMENT_PATH="/home/travisaw/travisaw.com/test/dev/synth-patch-name-generator"
  - PRODUCTION_PATH="/home/travisaw/travisaw.com/test/pro/synth-patch-name-generator"
  - SSH_USER="travisaw"
  - SSH_HOST="travisawagner.com"
  - DEPLOY_IGNORE="./.deployignore"
  - DEPLOY_PATH=$DEVELOPMENT_PATH
node_js:
- "node"
cache: npm
addons:
  ssh_known_hosts: travisawagner.com
before_install:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi
- openssl aes-256-cbc -K $encrypted_615321f5512c_key -iv $encrypted_615321f5512c_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script:
  - if [ $TRAVIS_BRANCH = "master" ]; then DEPLOY_PATH=$PRODUCTION_PATH; fi
  - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ --exclude-from=$DEPLOY_IGNORE $SSH_USER@$SSH_HOST:$DEPLOY_PATH
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^dev|master$"
